name: CI

on:
  push:
  pull_request:

jobs:

  ci:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'

    - uses: actions/checkout@v2

    - name: Cache protobuf build
      id: protocache
      uses: actions/cache@v2
      with:
        path: _vendor/protobuf-3.20.0
        key: protobuf-3.20.0

    - name: Compile protobuf
      if: steps.protocache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y autoconf automake libtool curl make g++ unzip

        mkdir -p _vendor
        curl -#fsSL https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protobuf-all-3.20.0.tar.gz | tar -xzvf - -C _vendor

        cd _vendor/protobuf-3.20.0
        ./configure
        make
        make -C conformance
        ls -l src/
        ls -l conformance/

    - run: make install && go mod tidy && go mod verify
    - run: git --no-pager diff --exit-code

    - run: go vet ./...

    - run: make genall
    - run: git --no-pager diff --exit-code

    - run: make test
    - run: git --no-pager diff --exit-code
